steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ArquiEmergentes', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ArquiEmergentes']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'ArquiEmergentes', '--image', 'gcr.io/$PROJECT_ID/ArquiEmergentes', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/ArquiEmergentes'

options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: bucket-emergentes